# Generated by Django 5.2.7 on 2026-10-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_booking_labour_quoted_booking_tax_rate_quoted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='offer_code_quoted',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='booking',
            name='offer_discount_quoted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
