# Generated by Django 5.2.7 on 2026-10-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_jobphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('services', models.ManyToManyField(blank=True, related_name='areas', to='portal.service')),
            ],
        ),
    ]
