window.SHIVA_CATALOG_PRODUCTS = [
  {
    id: "cp-plus-2mp-dome",
    brand: "CP Plus",
    model: "CP-UNC-DA21L3C-Q",
    title: "2MP Network IR Dome Camera",
    category: "CCTV",
    badge: "Popular",
    price: 2500,
    unit: "piece",
    priceLabel: "Rs. 2,500 onwards / piece",
    image: "assets/products/cp-plus-2mp-dome.png",
    art: "art-dome",
    specs: ["2MP 1920 x 1080 video", "30 m IR range", "PoE and IP67 rated", "Built-in mic support"]
  },
  {
    id: "hikvision-2mp-bullet",
    brand: "Hikvision",
    model: "DS-2CD1023G0E-I",
    title: "2MP Fixed Bullet Network Camera",
    category: "CCTV",
    badge: "IP Camera",
    price: 3200,
    unit: "piece",
    priceLabel: "Rs. 3,200 onwards / piece",
    image: "assets/products/hikvision-2mp-bullet.png",
    art: "art-bullet",
    specs: ["2MP progressive CMOS", "H.265+ compression", "DWDR and 3D DNR", "IP67 outdoor body"]
  },
  {
    id: "dahua-5mp-bullet",
    brand: "Dahua",
    model: "HAC-HFW1509TLM-IL-A",
    title: "5MP Smart Dual Light Bullet Camera",
    category: "CCTV",
    badge: "Upgrade",
    price: 3900,
    unit: "piece",
    priceLabel: "Rs. 3,900 onwards / piece",
    image: "assets/products/dahua-5mp-bullet.png",
    art: "art-bullet",
    specs: ["5MP 2880 x 1620 imaging", "IR and warm light up to 40 m", "Built-in mic option", "120 dB WDR and IP67"]
  },
  {
    id: "cp-plus-4ch-nvr",
    brand: "CP Plus",
    model: "CP-UNR-104F1",
    title: "4 Channel Network Video Recorder",
    category: "CCTV",
    badge: "NVR",
    price: 4500,
    unit: "piece",
    priceLabel: "Rs. 4,500 onwards / piece",
    image: "assets/products/cp-plus-4ch-nvr.jpg",
    art: "art-recorder",
    specs: ["4 IP camera inputs", "Up to 8MP preview/playback", "1 SATA HDD up to 8TB", "ONVIF multi-brand support"]
  },
  {
    id: "wd-purple-2tb",
    brand: "Western Digital",
    model: "WD Purple",
    title: "2TB Surveillance Hard Drive",
    category: "CCTV",
    badge: "Storage",
    price: 5400,
    unit: "piece",
    priceLabel: "Rs. 5,400 onwards / piece",
    image: "assets/products/wd-purple-2tb.png",
    art: "art-hdd",
    specs: ["Designed for 24x7 surveillance", "SATA 3.5 inch HDD", "AllFrame technology", "DVR/NVR storage planning"]
  },
  {
    id: "polycab-cctv-cable",
    brand: "Polycab",
    model: "CCTV/Data Cable",
    title: "CCTV and Data Cable with Laying",
    category: "CCTV",
    badge: "Per Meter",
    price: 45,
    unit: "meter",
    priceLabel: "Rs. 45 onwards / meter",
    image: "assets/products/polycab-cable.webp",
    art: "art-cable",
    specs: ["CCTV, coaxial and data options", "Copper conductor options", "Route marking and laying", "Final length after site check"]
  },
  {
    id: "tp-link-archer-c6",
    brand: "TP-Link",
    model: "Archer C6",
    title: "AC1200 Dual-Band Wi-Fi Router",
    category: "Networking",
    badge: "Wi-Fi",
    price: 2800,
    unit: "piece",
    priceLabel: "Rs. 2,800 onwards / piece",
    image: "assets/products/tp-link-archer-c6.jpg",
    art: "art-router",
    specs: ["867 Mbps at 5GHz", "400 Mbps at 2.4GHz", "MU-MIMO and Beamforming", "Access Point mode support"]
  },
  {
    id: "dlink-8port-switch",
    brand: "D-Link",
    model: "DGS-1008A",
    title: "8-Port Gigabit Desktop Switch",
    category: "Networking",
    badge: "LAN",
    price: 2200,
    unit: "piece",
    priceLabel: "Rs. 2,200 onwards / piece",
    image: "assets/products/dlink-dgs-1008a.png",
    art: "art-switch",
    specs: ["8 Gigabit Ethernet ports", "16 Gbps switching capacity", "Fanless silent design", "Green energy saving features"]
  },
  {
    id: "molex-cat6-cable",
    brand: "Molex",
    model: "PowerCat 6 UTP LSZH",
    title: "Cat 6 Structured LAN Cabling",
    category: "Networking",
    badge: "Cat 6",
    price: 65,
    unit: "meter",
    priceLabel: "Rs. 65 onwards / meter",
    image: "assets/products/molex-cat6-cable.webp",
    art: "art-cable",
    specs: ["8 copper conductors", "4 twisted pairs", "LSZH sheath option", "Testing and termination support"]
  },
  {
    id: "schneider-acti9-mcb",
    brand: "Schneider Electric",
    model: "Acti9 iK60N 2P 25A",
    title: "Miniature Circuit Breaker",
    category: "Electrical",
    badge: "30-35% Off",
    price: 850,
    unit: "piece",
    priceLabel: "Offer after 30-35% discount: Rs. 850 onwards / piece",
    image: "assets/products/schneider-acti9-mcb.jpg",
    art: "art-panel",
    offer: "MCB/protection offer: 30-35% discount on selected price-list items.",
    specs: ["2 pole, 25A, C curve", "6000A breaking capacity", "IEC/EN 60898-1 standard", "DB and panel integration"]
  },
  {
    id: "wipro-garnet-9w-bulb",
    brand: "Wipro",
    model: "Garnet 9W B22/E27",
    title: "LED Bulb for Home and Office",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 120,
    unit: "piece",
    priceLabel: "Offer price: Rs. 120 onwards / piece",
    image: "assets/products/wipro-garnet-9w-bulb.jpg",
    art: "art-panel",
    offer: "Lighting and electronics offer: up to 40% discount on selected items.",
    specs: ["9W LED bulb option", "B22 and E27 holder planning", "Cool white and warm white options", "Supply, fitting and replacement support"]
  },
  {
    id: "philips-led-batten-20w",
    brand: "Philips",
    model: "StarBright / SlimLine 20W",
    title: "LED Tubelight and Batten",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 420,
    unit: "piece",
    priceLabel: "Offer price: Rs. 420 onwards / piece",
    image: "assets/products/philips-led-batten.jpeg",
    art: "art-panel",
    offer: "Lighting and electronics offer: up to 40% discount on selected items.",
    specs: ["20W LED batten/tubelight options", "Uniform indoor illumination", "Wall or ceiling mounting", "Home, shop and office use"]
  },
  {
    id: "crompton-bldc-fan-1200",
    brand: "Crompton",
    model: "Energion Elevate 1200mm",
    title: "BLDC Ceiling Fan with Installation",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 2800,
    unit: "piece",
    priceLabel: "Offer price: Rs. 2,800 onwards / piece",
    image: "assets/products/crompton-bldc-fan.png",
    art: "art-panel",
    offer: "Fan and fixture offer: up to 40% discount on selected price-list items.",
    specs: ["1200mm sweep fan option", "Energy-saving BLDC motor", "Remote and regulator planning", "Installation, balancing and testing"]
  },
  {
    id: "anchor-roma-switch",
    brand: "Anchor by Panasonic",
    model: "Roma Classic 6A",
    title: "Modular Switch",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 90,
    unit: "piece",
    priceLabel: "Offer price: Rs. 90 onwards / piece",
    image: "assets/products/anchor-roma-switch.png",
    art: "art-panel",
    offer: "Switches and accessories offer: up to 40% discount on selected items.",
    specs: ["6A modular switch range", "Clean switchboard fitting", "Residential and office use", "Point replacement and new installation"]
  },
  {
    id: "anchor-roma-socket",
    brand: "Anchor by Panasonic",
    model: "Roma Classic 6A/16A",
    title: "Modular Socket",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 140,
    unit: "piece",
    priceLabel: "Offer price: Rs. 140 onwards / piece",
    image: "assets/products/anchor-roma-socket.png",
    art: "art-panel",
    offer: "Switches and accessories offer: up to 40% discount on selected items.",
    specs: ["6A and 16A socket options", "Switchboard and plate fitting", "Load-based socket selection", "Testing before handover"]
  },
  {
    id: "anchor-fan-regulator",
    brand: "Anchor by Panasonic",
    model: "Roma Classic Regulator",
    title: "Fan Regulator and Control",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 450,
    unit: "piece",
    priceLabel: "Offer price: Rs. 450 onwards / piece",
    image: "assets/products/anchor-fan-regulator.png",
    art: "art-panel",
    offer: "Switches and accessories offer: up to 40% discount on selected items.",
    specs: ["Modular fan regulator", "Speed control fitting", "Switchboard compatibility check", "Replacement and new point support"]
  },
  {
    id: "polycab-green-wire-15",
    brand: "Polycab",
    model: "Green Wire 1.5 sq mm",
    title: "Electrical House Wire",
    category: "Electrical",
    badge: "30-35% Off",
    price: 18,
    unit: "meter",
    priceLabel: "Offer after 30-35% discount: Rs. 18 onwards / meter",
    image: "assets/products/polycab-green-wire.webp",
    art: "art-cable",
    offer: "Wire offer: 30-35% discount on selected wire and cable price-list items.",
    specs: ["1.5 sq mm house wiring option", "HR-FR / LSH planning", "Lighting and low-load circuits", "Conduit routing and tagging support"]
  },
  {
    id: "polycab-fr-wire-25",
    brand: "Polycab",
    model: "FR / FRLS Copper Wire",
    title: "Power Wire and Cable",
    category: "Electrical",
    badge: "30-35% Off",
    price: 32,
    unit: "meter",
    priceLabel: "Offer after 30-35% discount: Rs. 32 onwards / meter",
    image: "assets/products/polycab-fr-wire.webp",
    art: "art-cable",
    offer: "Wire offer: 30-35% discount on selected wire and cable price-list items.",
    specs: ["2.5 sq mm and higher options", "Power socket and appliance circuits", "Copper conductor selection", "Length finalized after site measurement"]
  },
  {
    id: "polycab-green-wire-075",
    brand: "Polycab",
    model: "Green Wire 0.75 sq mm",
    title: "Light-Duty Electrical Wire",
    category: "Electrical",
    badge: "30-35% Off",
    price: 12,
    unit: "meter",
    priceLabel: "Offer after 30-35% discount: Rs. 12 onwards / meter",
    image: "assets/products/polycab-green-wire.webp",
    art: "art-cable",
    offer: "Wire offer: 30-35% discount on selected wire and cable price-list items.",
    specs: ["0.75 sq mm copper wire option", "Low-load internal wiring", "Suitable for control and light-duty circuits", "Final selection after load check"]
  },
  {
    id: "polycab-green-wire-10",
    brand: "Polycab",
    model: "Green Wire 1.0 sq mm",
    title: "Standard Electrical Wire",
    category: "Electrical",
    badge: "30-35% Off",
    price: 15,
    unit: "meter",
    priceLabel: "Offer after 30-35% discount: Rs. 15 onwards / meter",
    image: "assets/products/polycab-green-wire.webp",
    art: "art-cable",
    offer: "Wire offer: 30-35% discount on selected wire and cable price-list items.",
    specs: ["1.0 sq mm house wire option", "Lighting and low-load circuits", "FR / FRLS selection support", "Length finalized after site measurement"]
  },
  {
    id: "polycab-green-wire-40",
    brand: "Polycab",
    model: "Green Wire 4.0 sq mm",
    title: "Heavy Power Circuit Wire",
    category: "Electrical",
    badge: "30-35% Off",
    price: 55,
    unit: "meter",
    priceLabel: "Offer after 30-35% discount: Rs. 55 onwards / meter",
    image: "assets/products/polycab-fr-wire.webp",
    art: "art-cable",
    offer: "Wire offer: 30-35% discount on selected wire and cable price-list items.",
    specs: ["4.0 sq mm copper wire option", "AC, geyser and higher-load circuits", "Conduit and DB route planning", "Load verification before final supply"]
  },
  {
    id: "polycab-green-wire-60",
    brand: "Polycab",
    model: "Green Wire 6.0 sq mm",
    title: "High-Load Copper Wire",
    category: "Electrical",
    badge: "30-35% Off",
    price: 82,
    unit: "meter",
    priceLabel: "Offer after 30-35% discount: Rs. 82 onwards / meter",
    image: "assets/products/polycab-fr-wire.webp",
    art: "art-cable",
    offer: "Wire offer: 30-35% discount on selected wire and cable price-list items.",
    specs: ["6.0 sq mm copper wire option", "Main feed and high-load support", "MCB/RCCB coordination planning", "Final rating after site inspection"]
  },
  {
    id: "polycab-flexible-multicore",
    brand: "Polycab",
    model: "Flexible Multi-Core Cable",
    title: "Flexible Cable for Appliances and Controls",
    category: "Electrical",
    badge: "30-35% Off",
    price: 95,
    unit: "meter",
    priceLabel: "Offer after 30-35% discount: Rs. 95 onwards / meter",
    image: "assets/products/polycab-cable.webp",
    art: "art-cable",
    offer: "Wire and cable offer: 30-35% discount on selected price-list items.",
    specs: ["2 core, 3 core and multi-core options", "Appliance and control wiring support", "Copper conductor selection", "Final rate as per core count and sq mm"]
  },
  {
    id: "schneider-sp-mcb-range",
    brand: "Schneider / Legrand",
    model: "SP MCB 6A-32A",
    title: "Single Pole MCB Range",
    category: "Electrical",
    badge: "30-35% Off",
    price: 190,
    unit: "piece",
    priceLabel: "Offer after 30-35% discount: Rs. 190 onwards / piece",
    image: "assets/products/schneider-acti9-mcb.jpg",
    art: "art-panel",
    offer: "MCB/protection offer: 30-35% discount on selected price-list items.",
    specs: ["6A, 10A, 16A, 20A and 32A options", "B curve / C curve selection", "Lighting and socket circuit protection", "Final make as per availability and BOQ"]
  },
  {
    id: "schneider-dp-mcb-range",
    brand: "Schneider / Legrand",
    model: "DP MCB 32A-63A",
    title: "Double Pole MCB Range",
    category: "Electrical",
    badge: "30-35% Off",
    price: 650,
    unit: "piece",
    priceLabel: "Offer after 30-35% discount: Rs. 650 onwards / piece",
    image: "assets/products/schneider-acti9-mcb.jpg",
    art: "art-panel",
    offer: "MCB/protection offer: 30-35% discount on selected price-list items.",
    specs: ["32A, 40A and 63A DP options", "Single-phase incoming and sub-circuit use", "DIN rail mounting support", "Testing after installation"]
  },
  {
    id: "schneider-tp-mcb-range",
    brand: "Schneider / Legrand",
    model: "TP/FP MCB Range",
    title: "Three Phase MCB and Isolator Range",
    category: "Electrical",
    badge: "30-35% Off",
    price: 1450,
    unit: "piece",
    priceLabel: "Offer after 30-35% discount: Rs. 1,450 onwards / piece",
    image: "assets/products/schneider-acti9-mcb.jpg",
    art: "art-panel",
    offer: "MCB/protection offer: 30-35% discount on selected price-list items.",
    specs: ["TP and FP protection options", "Commercial and three-phase DB use", "Load and fault-level coordination", "Final model after panel inspection"]
  },
  {
    id: "db-spn-tpn-board",
    brand: "Schneider / Legrand / Equivalent",
    model: "SPN / TPN Distribution Board",
    title: "Distribution Board with MCB Planning",
    category: "Electrical",
    badge: "30-35% Off",
    price: 1400,
    unit: "board",
    priceLabel: "Offer after 30-35% discount: Rs. 1,400 onwards / board",
    image: "assets/products/schneider-acti9-mcb.jpg",
    art: "art-panel",
    offer: "DB and protection offer: 30-35% discount on selected price-list items.",
    specs: ["SPN and TPN DB options", "MCB/RCCB/RCBO layout planning", "Circuit labeling and testing", "Final quote after module count confirmation"]
  },
  {
    id: "schneider-acti9-rccb",
    brand: "Schneider Electric",
    model: "Acti9 xID 2P 40A 30mA",
    title: "RCCB / ELCB Earth Leakage Protection",
    category: "Electrical",
    badge: "30-35% Off",
    price: 2600,
    unit: "piece",
    priceLabel: "Offer after 30-35% discount: Rs. 2,600 onwards / piece",
    image: "assets/products/schneider-acti9-rccb.jpg",
    art: "art-panel",
    offer: "MCB/protection offer: 30-35% discount on selected price-list items.",
    specs: ["2 pole, 40A RCCB", "30mA earth leakage sensitivity", "DIN rail DB mounting", "Human safety and fire-risk protection"]
  },
  {
    id: "legrand-dx3-rcbo",
    brand: "Legrand",
    model: "DX3 2P 40A 30mA",
    title: "RCBO with Overload Protection",
    category: "Electrical",
    badge: "30-35% Off",
    price: 4800,
    unit: "piece",
    priceLabel: "Offer after 30-35% discount: Rs. 4,800 onwards / piece",
    image: "assets/products/legrand-dx3-rcbo.jpg",
    art: "art-panel",
    offer: "MCB/protection offer: 30-35% discount on selected price-list items.",
    specs: ["RCBO with earth leakage and overload protection", "40A, 30mA, C curve option", "6kA EN 61009 breaking capacity", "DB upgrade and circuit segregation support"]
  },
  {
    id: "philips-duraslim-downlight",
    brand: "Philips",
    model: "DuraSlim LED Downlight",
    title: "Interior LED Light Fixture",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 650,
    unit: "piece",
    priceLabel: "Offer price: Rs. 650 onwards / piece",
    image: "assets/products/philips-duraslim-downlight.jpeg",
    art: "art-panel",
    offer: "Lighting and fixture offer: up to 40% discount on selected items.",
    specs: ["Round and square downlight options", "7W, 12W, 15W, 18W and 22W planning", "False-ceiling cutout coordination", "Interior lighting layout support"]
  },
  {
    id: "gm-modular-fitting",
    brand: "GM Modular",
    model: "Modular Fitting Range",
    title: "Switchboard, Plate and Fixture Fitting",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 650,
    unit: "board",
    priceLabel: "Offer price: Rs. 650 onwards / board",
    image: "assets/products/gm-modular-switch.png",
    art: "art-panel",
    offer: "Switches, plates and fittings offer: up to 40% discount on selected items.",
    specs: ["Switchboard plate and module fitting", "Bulb, holder and fixture replacement", "Interior light and accessory support", "Neat finishing after installation"]
  },
  {
    id: "greatwhite-myrah-range",
    brand: "GreatWhite",
    model: "Myrah",
    title: "Premium Modular Switch Range",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 120,
    unit: "module",
    priceLabel: "Offer price: Rs. 120 onwards / module",
    image: "assets/products/greatwhite-myrah-brochure.png",
    art: "art-panel",
    offer: "Switches and accessories offer: up to 40% discount on selected price-list items.",
    specs: ["Premium modular switch and socket range", "Switch, socket, plate and accessory selection", "Home, office and interior projects", "Final rate as per module and plate combination"]
  },
  {
    id: "greatwhite-fiana-range",
    brand: "GreatWhite",
    model: "Fiana Feb 2026",
    title: "Fiana Switch and Socket Range",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 85,
    unit: "module",
    priceLabel: "Offer price: Rs. 85 onwards / module",
    image: "assets/products/greatwhite-fiana-price-list.png",
    art: "art-panel",
    offer: "Switches and accessories offer: up to 40% discount on selected price-list items.",
    specs: ["Fiana modular switch range", "Switches, sockets and plates", "Residential and commercial interiors", "Quotation as per uploaded price list and availability"]
  },
  {
    id: "greatwhite-arcus-range",
    brand: "GreatWhite",
    model: "Arcus",
    title: "Arcus Modular Electrical Range",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 95,
    unit: "module",
    priceLabel: "Offer price: Rs. 95 onwards / module",
    image: "assets/products/greatwhite-arcus-price-list.png",
    art: "art-panel",
    offer: "Switches and accessories offer: up to 40% discount on selected price-list items.",
    specs: ["Arcus modular switch and plate range", "Color and finish selection support", "Switchboard planning and fitting", "Final rate after module count confirmation"]
  },
  {
    id: "greatwhite-trivo-range",
    brand: "GreatWhite",
    model: "Trivo Feb 2026",
    title: "Trivo Modular Switch Range",
    category: "Electrical",
    badge: "Up to 40% Off",
    price: 80,
    unit: "module",
    priceLabel: "Offer price: Rs. 80 onwards / module",
    image: "assets/products/greatwhite-trivo-price-list.png",
    art: "art-panel",
    offer: "Switches and accessories offer: up to 40% discount on selected price-list items.",
    specs: ["Trivo modular switches and accessories", "Switch, socket and plate options", "Renovation and new-project support", "Final rate as per exact SKU and stock"]
  },
  {
    id: "wipro-smart-switch-module",
    brand: "Wipro",
    model: "Smart Switch Module",
    title: "Home Automation Switch Module",
    category: "Electronics",
    badge: "Up to 40% Off",
    price: 1900,
    unit: "point",
    priceLabel: "Offer price: Rs. 1,900 onwards / point",
    image: "assets/products/wipro-smart-switch-module.jpg",
    art: "art-panel",
    offer: "Smart electronics offer: up to 40% discount on selected automation items.",
    specs: ["2 node, 4 node and 3+1 node options", "2.4GHz Wi-Fi control", "Works with existing manual switches", "App and voice-control setup support"]
  },
  {
    id: "schneider-enmod1p-energy-monitor",
    brand: "Schneider Electric",
    model: "ENMOD1P Wiser EMD",
    title: "Wi-Fi Energy Monitoring Device",
    category: "Electronics",
    badge: "Flash Offer",
    price: 16500,
    unit: "setup",
    priceLabel: "Flash offer price: Rs. 16,500 onwards / setup",
    image: "assets/products/schneider-enmod1p-video.jpg",
    art: "art-panel",
    offer: "Flash home automation offer: up to 40% discount on selected ENMOD1P energy monitoring setups.",
    videoUrl: "https://www.youtube.com/watch?v=ZhjxQKF7su8",
    specs: ["6 channel, 1 pole energy monitoring device", "Wi-Fi connected Wiser app support", "DIN rail mounting inside distribution board", "Monitors voltage, current, power factor and energy"]
  },
  {
    id: "schneider-wiser-automation",
    brand: "Schneider Electric",
    model: "Wiser Smart Home",
    title: "Premium Home Automation Planning",
    category: "Electronics",
    badge: "Up to 40% Off",
    price: 4500,
    unit: "setup",
    priceLabel: "Offer price: Rs. 4,500 onwards / setup",
    image: "assets/products/schneider-wiser-home.jpg",
    art: "art-panel",
    offer: "Smart electronics offer: up to 40% discount on selected automation items.",
    specs: ["Lighting, fan and appliance automation planning", "App and voice-control ecosystem", "Scene and schedule configuration", "Retrofit and new-home consultation"]
  },
  {
    id: "wipro-smart-wifi-plug",
    brand: "Wipro",
    model: "Wi-Fi Smart Plug 10A/16A",
    title: "Smart Plug for Appliance Automation",
    category: "Electronics",
    badge: "Up to 40% Off",
    price: 950,
    unit: "piece",
    priceLabel: "Offer price: Rs. 950 onwards / piece",
    image: "assets/products/wipro-smart-switch-module.jpg",
    art: "art-panel",
    offer: "Electronics offer: up to 40% discount on selected smart-home items.",
    specs: ["10A and 16A smart plug options", "Scheduling and app control", "Voice assistant setup support", "Load suitability check before supply"]
  },
  {
    id: "wipro-smart-extension-board",
    brand: "Wipro",
    model: "Smart Wi-Fi Extension Board",
    title: "Smart Extension Board",
    category: "Electronics",
    badge: "Up to 40% Off",
    price: 1900,
    unit: "piece",
    priceLabel: "Offer price: Rs. 1,900 onwards / piece",
    image: "assets/products/wipro-smart-switch-module.jpg",
    art: "art-ups",
    offer: "Electronics offer: up to 40% discount on selected smart-home items.",
    specs: ["4 socket / 3 socket + USB options", "Scheduling and voice control", "Office and home appliance support", "Final model as per stock and load"]
  },
  {
    id: "smart-lighting-controller",
    brand: "Wipro / Schneider / Equivalent",
    model: "Smart Lighting Control",
    title: "Smart Lighting Controller",
    category: "Electronics",
    badge: "Up to 40% Off",
    price: 1500,
    unit: "point",
    priceLabel: "Offer price: Rs. 1,500 onwards / point",
    image: "assets/products/schneider-wiser-home.jpg",
    art: "art-panel",
    offer: "Electronics offer: up to 40% discount on selected lighting-control items.",
    specs: ["App-based light control", "Scene and schedule setup", "Switch-module and controller options", "Retrofit consultation included"]
  },
  {
    id: "led-strip-profile-controller",
    brand: "Wipro / Philips / Equivalent",
    model: "LED Strip and Profile Setup",
    title: "Decorative LED Strip and Profile Lighting",
    category: "Electronics",
    badge: "Up to 40% Off",
    price: 1450,
    unit: "setup",
    priceLabel: "Offer price: Rs. 1,450 onwards / setup",
    image: "assets/products/philips-duraslim-downlight.jpeg",
    art: "art-panel",
    offer: "Lighting and electronics offer: up to 40% discount on selected items.",
    specs: ["LED strip, profile and driver planning", "False ceiling and interior lighting support", "Warm, neutral and cool white options", "Final quote after length measurement"]
  },
  {
    id: "apc-bx600c",
    brand: "APC by Schneider Electric",
    model: "BX600C-IN",
    title: "600VA Back-UPS Power Backup",
    category: "Electronics",
    badge: "Up to 40% Off",
    price: 3800,
    unit: "piece",
    priceLabel: "Offer price: Rs. 3,800 onwards / piece",
    image: "assets/products/apc-bx600c.jpg",
    art: "art-ups",
    offer: "Electronics offer: up to 40% discount on selected UPS and backup items.",
    specs: ["600VA / 360W backup", "230V India model", "3 India output outlets", "Useful for CCTV and network loads"]
  },
  {
    id: "matrix-nenx312",
    brand: "Matrix",
    model: "ETERNITY NENX312",
    title: "Hybrid IP-PBX Communication System",
    category: "Communication",
    badge: "EPABX",
    price: 38000,
    unit: "setup",
    priceLabel: "Rs. 38,000 onwards / setup",
    image: "assets/products/matrix-nenx312.webp",
    art: "art-epabx",
    specs: ["3 FXO and 12 FXS ports", "2 GSM/3G/4G ports", "50 IP users", "4 voicemail channels"]
  },
  {
    id: "grandstream-ucm6202",
    brand: "Grandstream",
    model: "UCM6202",
    title: "IP PBX for Office Communication",
    category: "Communication",
    badge: "VoIP",
    price: 26500,
    unit: "setup",
    priceLabel: "Rs. 26,500 onwards / setup",
    image: "assets/products/grandstream-ucm6202.png",
    art: "art-epabx",
    specs: ["Up to 500 users", "2 FXO and 2 FXS ports", "Dual Gigabit network ports", "Queue, IVR and call recording"]
  }
];
